name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: msaggu204.github.io

      - name: Build
        run: npm run build
        working-directory: msaggu204.github.io

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: 'msaggu204.github.io/dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
